# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 20bd8b5bedb6b51ad8553abc60112a759c0e07f99f12242d97200f12e9ae03ccf8439fd8c297b912e383ac525edacd9a986527a478729d64ecc80bc521eeeaf3

test:
  secret_key_base: 3b92c9556be30b9c39e554712865cb7041a41e71071cab83b9fcd5a84a57ea8b55a62cc07a60f1fffee26e0b8c9855a14df5ae61e09c42a4239fd55061af7d6f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
